-- MySQL Script generated by MySQL Workbench
-- seg 07 mai 2018 17:24:44 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cni_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cni_db` ;

-- -----------------------------------------------------
-- Schema cni_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cni_db` DEFAULT CHARACTER SET utf8 ;
USE `cni_db` ;

-- -----------------------------------------------------
-- Table `cni_db`.`professores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cni_db`.`professores` ;

CREATE TABLE IF NOT EXISTS `cni_db`.`professores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(225) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `access` INT NULL,
  `password` VARCHAR(60) NOT NULL,
  `remember_token` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cni_db`.`materias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cni_db`.`materias` ;

CREATE TABLE IF NOT EXISTS `cni_db`.`materias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cni_db`.`dias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cni_db`.`dias` ;

CREATE TABLE IF NOT EXISTS `cni_db`.`dias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cni_db`.`horarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cni_db`.`horarios` ;

CREATE TABLE IF NOT EXISTS `cni_db`.`horarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `materias_id` INT NOT NULL,
  `start` TIME(5) NOT NULL,
  `end` TIME(5) NOT NULL,
  `dias_id` INT NOT NULL,
  PRIMARY KEY (`id`, `materias_id`, `dias_id`),
  INDEX `fk_horarios_materias1_idx` (`materias_id` ASC),
  INDEX `fk_horarios_dias1_idx` (`dias_id` ASC),
  CONSTRAINT `fk_horarios_materias1`
    FOREIGN KEY (`materias_id`)
    REFERENCES `cni_db`.`materias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_horarios_dias1`
    FOREIGN KEY (`dias_id`)
    REFERENCES `cni_db`.`dias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cni_db`.`alunos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cni_db`.`alunos` ;

CREATE TABLE IF NOT EXISTS `cni_db`.`alunos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `matricula` VARCHAR(20) NOT NULL,
  `nome` VARCHAR(60) NOT NULL,
  `nascimento` VARCHAR(15) NULL,
  `situacao` TINYINT(1) NOT NULL DEFAULT 1,
  `telefone` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cni_db`.`horarios_has_alunos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cni_db`.`horarios_has_alunos` ;

CREATE TABLE IF NOT EXISTS `cni_db`.`horarios_has_alunos` (
  `horarios_id` INT NOT NULL,
  `alunos_id` INT NOT NULL,
  PRIMARY KEY (`horarios_id`, `alunos_id`),
  INDEX `fk_horarios_has_alunos_alunos1_idx` (`alunos_id` ASC),
  INDEX `fk_horarios_has_alunos_horarios_idx` (`horarios_id` ASC),
  CONSTRAINT `fk_horarios_has_alunos_horarios`
    FOREIGN KEY (`horarios_id`)
    REFERENCES `cni_db`.`horarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_horarios_has_alunos_alunos1`
    FOREIGN KEY (`alunos_id`)
    REFERENCES `cni_db`.`alunos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cni_db`.`ocorrencias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cni_db`.`ocorrencias` ;

CREATE TABLE IF NOT EXISTS `cni_db`.`ocorrencias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `professores_id` INT NOT NULL,
  `alunos_id` INT NOT NULL,
  `descricao` VARCHAR(510) NULL,
  `horarios_id` INT NOT NULL,
  PRIMARY KEY (`id`, `professores_id`, `alunos_id`, `horarios_id`),
  INDEX `fk_ocorrencias_professores1_idx` (`professores_id` ASC),
  INDEX `fk_ocorrencias_alunos1_idx` (`alunos_id` ASC),
  INDEX `fk_ocorrencias_horarios1_idx` (`horarios_id` ASC),
  CONSTRAINT `fk_ocorrencias_professores1`
    FOREIGN KEY (`professores_id`)
    REFERENCES `cni_db`.`professores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ocorrencias_alunos1`
    FOREIGN KEY (`alunos_id`)
    REFERENCES `cni_db`.`alunos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ocorrencias_horarios1`
    FOREIGN KEY (`horarios_id`)
    REFERENCES `cni_db`.`horarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cni_db`.`relatorios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cni_db`.`relatorios` ;

CREATE TABLE IF NOT EXISTS `cni_db`.`relatorios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `horarios_id` INT NOT NULL,
  PRIMARY KEY (`id`, `horarios_id`),
  INDEX `fk_relatorios_horarios1_idx` (`horarios_id` ASC),
  CONSTRAINT `fk_relatorios_horarios1`
    FOREIGN KEY (`horarios_id`)
    REFERENCES `cni_db`.`horarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cni_db`.`situacoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cni_db`.`situacoes` ;

CREATE TABLE IF NOT EXISTS `cni_db`.`situacoes` (
  `id` TINYINT(2) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cni_db`.`relatorios_has_alunos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cni_db`.`relatorios_has_alunos` ;

CREATE TABLE IF NOT EXISTS `cni_db`.`relatorios_has_alunos` (
  `relatorios_id` INT NOT NULL,
  `alunos_id` INT NOT NULL,
  `situacoes_id` TINYINT(2) NOT NULL,
  PRIMARY KEY (`relatorios_id`, `alunos_id`, `situacoes_id`),
  INDEX `fk_relatorios_has_alunos_alunos1_idx` (`alunos_id` ASC),
  INDEX `fk_relatorios_has_alunos_relatorios1_idx` (`relatorios_id` ASC),
  INDEX `fk_relatorios_has_alunos_situacoes1_idx` (`situacoes_id` ASC),
  CONSTRAINT `fk_relatorios_has_alunos_relatorios1`
    FOREIGN KEY (`relatorios_id`)
    REFERENCES `cni_db`.`relatorios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_relatorios_has_alunos_alunos1`
    FOREIGN KEY (`alunos_id`)
    REFERENCES `cni_db`.`alunos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_relatorios_has_alunos_situacoes1`
    FOREIGN KEY (`situacoes_id`)
    REFERENCES `cni_db`.`situacoes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cni_db`.`conteudo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cni_db`.`conteudo` ;

CREATE TABLE IF NOT EXISTS `cni_db`.`conteudo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `conteudo` TEXT(500) NOT NULL,
  `data` DATE NOT NULL,
  `professores_id` INT NOT NULL,
  `horarios_id` INT NOT NULL,
  PRIMARY KEY (`id`, `professores_id`, `horarios_id`),
  INDEX `fk_conteudo_professores1_idx` (`professores_id` ASC),
  INDEX `fk_conteudo_horarios1_idx` (`horarios_id` ASC),
  CONSTRAINT `fk_conteudo_professores1`
    FOREIGN KEY (`professores_id`)
    REFERENCES `cni_db`.`professores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_conteudo_horarios1`
    FOREIGN KEY (`horarios_id`)
    REFERENCES `cni_db`.`horarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cni_db`.`advertencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cni_db`.`advertencia` ;

CREATE TABLE IF NOT EXISTS `cni_db`.`advertencia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `ocorrencia` TEXT(500) NOT NULL,
  `professores_id` INT NOT NULL,
  `alunos_id` INT NOT NULL,
  PRIMARY KEY (`id`, `professores_id`, `alunos_id`),
  INDEX `fk_advertencia_professores1_idx` (`professores_id` ASC),
  INDEX `fk_advertencia_alunos1_idx` (`alunos_id` ASC),
  CONSTRAINT `fk_advertencia_professores1`
    FOREIGN KEY (`professores_id`)
    REFERENCES `cni_db`.`professores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_advertencia_alunos1`
    FOREIGN KEY (`alunos_id`)
    REFERENCES `cni_db`.`alunos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
